
#define DOO_PRODUCT_VERSION_MAJOR 1
#define DOO_PRODUCT_VERSION_MINOR 0
#define DOO_PRODUCT_VERSION_WHAT  0
#define DOO_PRODUCT_VERSION_BUILD 0
#define DOO_PRODUCT_VERSION DOO_PRODUCT_VERSION_MAJOR,DOO_PRODUCT_VERSION_MINOR,DOO_PRODUCT_VERSION_WHAT,DOO_PRODUCT_VERSION_BUILD

#define _VERSION_STR(a,b,c,d)   #a "." #b "." #c "." #d
#define VERSION_STR(a,b,c,d)    _VERSION_STR(a,b,c,d)

#define DOO_PRODUCT_VERSION_STRING VERSION_STR(DOO_PRODUCT_VERSION_MAJOR,DOO_PRODUCT_VERSION_MINOR,DOO_PRODUCT_VERSION_WHAT,DOO_PRODUCT_VERSION_BUILD)

#define DOO_COPYRIGHT "(c)2012 " DOO_COMPANY_NAME
#define DOO_PRODUCT_NAME "doo"
#define DOO_COMPANY_NAME "doo GmbH"

